# Nome da aplicação (usado pelo Spring Boot internamente)
spring.application.name=budgeting

# Configuração do Hibernate:
# "update" ? cria/atualiza tabelas automaticamente com base nas entidades
# CUIDADO: em produção o ideal é usar "validate" ou migrations (Flyway/Liquibase)(tabelas ja criadas)
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os SQLs executados (debug)
spring.jpa.show-sql=true

# API Key da OpenAI (lida da variável de ambiente)
# Nunca colocar a chave direto no código
# OBS:
# Está sem tokens no momento
spring.ai.openai.api-key=${OPENAI_API_KEY}

# Modelo de chat usado (leve, rápido e barato)
spring.ai.openai.chat.options.model=gpt-4o-mini

# Define que a resposta do chat será texto simples
spring.ai.openai.chat.options.response-format.type=TEXT


# =========================
# TRANSCRIÇÃO DE ÁUDIO
# =========================

# Define que o provider de transcrição será OpenAI (não precisaria usar no momento porque o sistema ja sabe, mas é uma boa prática sempre informar)
spring.ai.model.audio.transcription=openai

# Modelo de transcrição (Whisper)
spring.ai.openai.audio.transcription.options.model=whisper-1

# Idioma esperado do áudio (melhora precisão, mas não diferencia entre português de Portugaal ou do Brasil)
spring.ai.openai.audio.transcription.options.language=pt

# Temperatura = 0 ? resposta mais determinística (menos variação)
# Temperatura maior = Mais alucinação
spring.ai.openai.audio.transcription.options.temperature=0

# Formato da resposta (texto puro)
spring.ai.openai.audio.transcription.options.response-format=text

# Prompt que guia o modelo durante a transcrição
# Aqui está sendo "ensinando" o contexto do áudio
spring.ai.openai.audio.transcription.options.prompt=Áudio em português brasileiro.\
  Áudio contém descrição de gastos financeiros. \
  As frases geralmente contêm: \
   - um valor em reais (número + "reais"); \
   - uma ação (gastei, paguei, comprei); \
   - um local ou estabelecimento (mercado, farmácia, restaurante, loja, etc.).


# =========================
# TEXT-TO-SPEECH (fala)
# =========================

# Define que o provider de geração de áudio será OpenAI
spring.ai.model.audio.speech=openai

# Modelo de voz (TTS - text-to-speech)
spring.ai.openai.audio.speech.options.model=gpt-4o-mini-tts

# Voz utilizada (ex: "nova")
spring.ai.openai.audio.speech.options.voice=nova

# Velocidade da fala (1.0 = normal, 1.2 = mais rápida)
spring.ai.openai.audio.speech.options.speed=1.2

# Formato do áudio gerado
spring.ai.openai.audio.speech.options.response-format=mp3


# =========================
# DEBUG
# =========================

# Mostra logs detalhados do Spring AI
# Muito útil para ver requisições, respostas e tool calling
logging.level.org.springframework.ai=DEBUG